/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as CompanionIndexImport } from './routes/companion/index'
import { Route as AccountNameIndexImport } from './routes/$accountName/index'
import { Route as SettingsProfileImport } from './routes/settings/profile'
import { Route as CompanionCreateImport } from './routes/companion/create'
import { Route as AccountNameCompanionNameImport } from './routes/$accountName/$companionName'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompanionIndexRoute = CompanionIndexImport.update({
  id: '/companion/',
  path: '/companion/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameIndexRoute = AccountNameIndexImport.update({
  id: '/$accountName/',
  path: '/$accountName/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const CompanionCreateRoute = CompanionCreateImport.update({
  id: '/companion/create',
  path: '/companion/create',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameCompanionNameRoute = AccountNameCompanionNameImport.update({
  id: '/$accountName/$companionName',
  path: '/$accountName/$companionName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/$companionName': {
      id: '/$accountName/$companionName'
      path: '/$accountName/$companionName'
      fullPath: '/$accountName/$companionName'
      preLoaderRoute: typeof AccountNameCompanionNameImport
      parentRoute: typeof rootRoute
    }
    '/companion/create': {
      id: '/companion/create'
      path: '/companion/create'
      fullPath: '/companion/create'
      preLoaderRoute: typeof CompanionCreateImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/': {
      id: '/$accountName/'
      path: '/$accountName'
      fullPath: '/$accountName'
      preLoaderRoute: typeof AccountNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/companion/': {
      id: '/companion/'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/companion': typeof CompanionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/companion': typeof CompanionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/$accountName/': typeof AccountNameIndexRoute
  '/companion/': typeof CompanionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$accountName/$companionName'
    | '/companion/create'
    | '/settings/profile'
    | '/$accountName'
    | '/companion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$accountName/$companionName'
    | '/companion/create'
    | '/settings/profile'
    | '/$accountName'
    | '/companion'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$accountName/$companionName'
    | '/companion/create'
    | '/settings/profile'
    | '/$accountName/'
    | '/companion/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AccountNameCompanionNameRoute: typeof AccountNameCompanionNameRoute
  CompanionCreateRoute: typeof CompanionCreateRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  AccountNameIndexRoute: typeof AccountNameIndexRoute
  CompanionIndexRoute: typeof CompanionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AccountNameCompanionNameRoute: AccountNameCompanionNameRoute,
  CompanionCreateRoute: CompanionCreateRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  AccountNameIndexRoute: AccountNameIndexRoute,
  CompanionIndexRoute: CompanionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/$accountName/$companionName",
        "/companion/create",
        "/settings/profile",
        "/$accountName/",
        "/companion/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$accountName/$companionName": {
      "filePath": "$accountName/$companionName.tsx"
    },
    "/companion/create": {
      "filePath": "companion/create.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.tsx"
    },
    "/$accountName/": {
      "filePath": "$accountName/index.tsx"
    },
    "/companion/": {
      "filePath": "companion/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
