/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as ToolIndexImport } from './routes/tool/index'
import { Route as CompanionIndexImport } from './routes/companion/index'
import { Route as AccountNameIndexImport } from './routes/$accountName/index'
import { Route as ToolCreateImport } from './routes/tool/create'
import { Route as SettingsProfileImport } from './routes/settings/profile'
import { Route as CompanionCreateImport } from './routes/companion/create'
import { Route as AccountNameToolsIndexImport } from './routes/$accountName/tools/index'
import { Route as AccountNameCompanionsIndexImport } from './routes/$accountName/companions/index'
import { Route as AccountNameToolsToolNameImport } from './routes/$accountName/tools/$toolName'
import { Route as AccountNameCompanionsCompanionNameImport } from './routes/$accountName/companions/$companionName'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolIndexRoute = ToolIndexImport.update({
  id: '/tool/',
  path: '/tool/',
  getParentRoute: () => rootRoute,
} as any)

const CompanionIndexRoute = CompanionIndexImport.update({
  id: '/companion/',
  path: '/companion/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameIndexRoute = AccountNameIndexImport.update({
  id: '/$accountName/',
  path: '/$accountName/',
  getParentRoute: () => rootRoute,
} as any)

const ToolCreateRoute = ToolCreateImport.update({
  id: '/tool/create',
  path: '/tool/create',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const CompanionCreateRoute = CompanionCreateImport.update({
  id: '/companion/create',
  path: '/companion/create',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameToolsIndexRoute = AccountNameToolsIndexImport.update({
  id: '/$accountName/tools/',
  path: '/$accountName/tools/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameCompanionsIndexRoute = AccountNameCompanionsIndexImport.update(
  {
    id: '/$accountName/companions/',
    path: '/$accountName/companions/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AccountNameToolsToolNameRoute = AccountNameToolsToolNameImport.update({
  id: '/$accountName/tools/$toolName',
  path: '/$accountName/tools/$toolName',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameCompanionsCompanionNameRoute =
  AccountNameCompanionsCompanionNameImport.update({
    id: '/$accountName/companions/$companionName',
    path: '/$accountName/companions/$companionName',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/companion/create': {
      id: '/companion/create'
      path: '/companion/create'
      fullPath: '/companion/create'
      preLoaderRoute: typeof CompanionCreateImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
    '/tool/create': {
      id: '/tool/create'
      path: '/tool/create'
      fullPath: '/tool/create'
      preLoaderRoute: typeof ToolCreateImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/': {
      id: '/$accountName/'
      path: '/$accountName'
      fullPath: '/$accountName'
      preLoaderRoute: typeof AccountNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/companion/': {
      id: '/companion/'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionIndexImport
      parentRoute: typeof rootRoute
    }
    '/tool/': {
      id: '/tool/'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolIndexImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/companions/$companionName': {
      id: '/$accountName/companions/$companionName'
      path: '/$accountName/companions/$companionName'
      fullPath: '/$accountName/companions/$companionName'
      preLoaderRoute: typeof AccountNameCompanionsCompanionNameImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/tools/$toolName': {
      id: '/$accountName/tools/$toolName'
      path: '/$accountName/tools/$toolName'
      fullPath: '/$accountName/tools/$toolName'
      preLoaderRoute: typeof AccountNameToolsToolNameImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/companions/': {
      id: '/$accountName/companions/'
      path: '/$accountName/companions'
      fullPath: '/$accountName/companions'
      preLoaderRoute: typeof AccountNameCompanionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/tools/': {
      id: '/$accountName/tools/'
      path: '/$accountName/tools'
      fullPath: '/$accountName/tools'
      preLoaderRoute: typeof AccountNameToolsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tool/create': typeof ToolCreateRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/companion': typeof CompanionIndexRoute
  '/tool': typeof ToolIndexRoute
  '/$accountName/companions/$companionName': typeof AccountNameCompanionsCompanionNameRoute
  '/$accountName/tools/$toolName': typeof AccountNameToolsToolNameRoute
  '/$accountName/companions': typeof AccountNameCompanionsIndexRoute
  '/$accountName/tools': typeof AccountNameToolsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tool/create': typeof ToolCreateRoute
  '/$accountName': typeof AccountNameIndexRoute
  '/companion': typeof CompanionIndexRoute
  '/tool': typeof ToolIndexRoute
  '/$accountName/companions/$companionName': typeof AccountNameCompanionsCompanionNameRoute
  '/$accountName/tools/$toolName': typeof AccountNameToolsToolNameRoute
  '/$accountName/companions': typeof AccountNameCompanionsIndexRoute
  '/$accountName/tools': typeof AccountNameToolsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companion/create': typeof CompanionCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tool/create': typeof ToolCreateRoute
  '/$accountName/': typeof AccountNameIndexRoute
  '/companion/': typeof CompanionIndexRoute
  '/tool/': typeof ToolIndexRoute
  '/$accountName/companions/$companionName': typeof AccountNameCompanionsCompanionNameRoute
  '/$accountName/tools/$toolName': typeof AccountNameToolsToolNameRoute
  '/$accountName/companions/': typeof AccountNameCompanionsIndexRoute
  '/$accountName/tools/': typeof AccountNameToolsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companion/create'
    | '/settings/profile'
    | '/tool/create'
    | '/$accountName'
    | '/companion'
    | '/tool'
    | '/$accountName/companions/$companionName'
    | '/$accountName/tools/$toolName'
    | '/$accountName/companions'
    | '/$accountName/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/companion/create'
    | '/settings/profile'
    | '/tool/create'
    | '/$accountName'
    | '/companion'
    | '/tool'
    | '/$accountName/companions/$companionName'
    | '/$accountName/tools/$toolName'
    | '/$accountName/companions'
    | '/$accountName/tools'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/companion/create'
    | '/settings/profile'
    | '/tool/create'
    | '/$accountName/'
    | '/companion/'
    | '/tool/'
    | '/$accountName/companions/$companionName'
    | '/$accountName/tools/$toolName'
    | '/$accountName/companions/'
    | '/$accountName/tools/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CompanionCreateRoute: typeof CompanionCreateRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ToolCreateRoute: typeof ToolCreateRoute
  AccountNameIndexRoute: typeof AccountNameIndexRoute
  CompanionIndexRoute: typeof CompanionIndexRoute
  ToolIndexRoute: typeof ToolIndexRoute
  AccountNameCompanionsCompanionNameRoute: typeof AccountNameCompanionsCompanionNameRoute
  AccountNameToolsToolNameRoute: typeof AccountNameToolsToolNameRoute
  AccountNameCompanionsIndexRoute: typeof AccountNameCompanionsIndexRoute
  AccountNameToolsIndexRoute: typeof AccountNameToolsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CompanionCreateRoute: CompanionCreateRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ToolCreateRoute: ToolCreateRoute,
  AccountNameIndexRoute: AccountNameIndexRoute,
  CompanionIndexRoute: CompanionIndexRoute,
  ToolIndexRoute: ToolIndexRoute,
  AccountNameCompanionsCompanionNameRoute:
    AccountNameCompanionsCompanionNameRoute,
  AccountNameToolsToolNameRoute: AccountNameToolsToolNameRoute,
  AccountNameCompanionsIndexRoute: AccountNameCompanionsIndexRoute,
  AccountNameToolsIndexRoute: AccountNameToolsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/companion/create",
        "/settings/profile",
        "/tool/create",
        "/$accountName/",
        "/companion/",
        "/tool/",
        "/$accountName/companions/$companionName",
        "/$accountName/tools/$toolName",
        "/$accountName/companions/",
        "/$accountName/tools/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/companion/create": {
      "filePath": "companion/create.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.tsx"
    },
    "/tool/create": {
      "filePath": "tool/create.tsx"
    },
    "/$accountName/": {
      "filePath": "$accountName/index.tsx"
    },
    "/companion/": {
      "filePath": "companion/index.tsx"
    },
    "/tool/": {
      "filePath": "tool/index.tsx"
    },
    "/$accountName/companions/$companionName": {
      "filePath": "$accountName/companions/$companionName.tsx"
    },
    "/$accountName/tools/$toolName": {
      "filePath": "$accountName/tools/$toolName.tsx"
    },
    "/$accountName/companions/": {
      "filePath": "$accountName/companions/index.tsx"
    },
    "/$accountName/tools/": {
      "filePath": "$accountName/tools/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
