/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as CompanionImport } from './routes/companion'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AccountNameIndexImport } from './routes/$accountName/index'
import { Route as AccountNameCompanionNameImport } from './routes/$accountName/$companionName'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CompanionRoute = CompanionImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameIndexRoute = AccountNameIndexImport.update({
  id: '/$accountName/',
  path: '/$accountName/',
  getParentRoute: () => rootRoute,
} as any)

const AccountNameCompanionNameRoute = AccountNameCompanionNameImport.update({
  id: '/$accountName/$companionName',
  path: '/$accountName/$companionName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/$companionName': {
      id: '/$accountName/$companionName'
      path: '/$accountName/$companionName'
      fullPath: '/$accountName/$companionName'
      preLoaderRoute: typeof AccountNameCompanionNameImport
      parentRoute: typeof rootRoute
    }
    '/$accountName/': {
      id: '/$accountName/'
      path: '/$accountName'
      fullPath: '/$accountName'
      preLoaderRoute: typeof AccountNameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/$accountName': typeof AccountNameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/$accountName': typeof AccountNameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companion': typeof CompanionRoute
  '/login': typeof LoginRoute
  '/$accountName/$companionName': typeof AccountNameCompanionNameRoute
  '/$accountName/': typeof AccountNameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/companion'
    | '/login'
    | '/$accountName/$companionName'
    | '/$accountName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/companion'
    | '/login'
    | '/$accountName/$companionName'
    | '/$accountName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/companion'
    | '/login'
    | '/$accountName/$companionName'
    | '/$accountName/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompanionRoute: typeof CompanionRoute
  LoginRoute: typeof LoginRoute
  AccountNameCompanionNameRoute: typeof AccountNameCompanionNameRoute
  AccountNameIndexRoute: typeof AccountNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompanionRoute: CompanionRoute,
  LoginRoute: LoginRoute,
  AccountNameCompanionNameRoute: AccountNameCompanionNameRoute,
  AccountNameIndexRoute: AccountNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/companion",
        "/login",
        "/$accountName/$companionName",
        "/$accountName/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/companion": {
      "filePath": "companion.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$accountName/$companionName": {
      "filePath": "$accountName/$companionName.tsx"
    },
    "/$accountName/": {
      "filePath": "$accountName/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
