name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  backend:
    defaults:
      run:
        working-directory: backend

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: aiba_test
          POSTGRES_USER: aiba
          POSTGRES_PASSWORD: aiba
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
          working-directory: backend

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Lint code for consistent style
        run: bin/rubocop -f github

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_NAME: aiba_test
          DB_USER: aiba
          DB_PASS: aiba
          DB_HOST: localhost
          DB_PORT: '5432'
        run: bin/rails db:test:prepare test

  frontend:
    defaults:
      run:
        working-directory: frontend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.tool-versions

      - name: Install dependencies
        run: npm install

      - name: Lint code for consistent style
        run: npm run lint

      - name: Run tests
        run: npm run test

